package Soroban;

import javax.microedition.midlet.*;
import javax.microedition.lcdui.*;

public class UsaKetaTama extends MIDlet 
{
    
    Display display;
    
    public UsaKetaTama() 
    {
    }
    
// --- This section is auto-generated by NetBeans IDE. Do not modify or you may lose your changes.//<editor-fold id="MVDMethods" defaultstate="collapsed" desc="This section is auto-generated by NetBeans IDE.">//GEN-BEGIN:MVDMethods
    /**
     * This method initializes UI of the application.
     */
    private void initialize() {
    }
    
// --- This is the end of auto-generated section.//</editor-fold>//GEN-END:MVDMethods
    
    public void startApp() 
    {
        initialize();
        KetaTama kt = new KetaTama(this);
        display=Display.getDisplay(this);
        display.setCurrent(kt);
    }
    
    public void pauseApp() 
    {
    }
    
    public void destroyApp(boolean unconditional) 
    {
    }
    
}
